[package]
name = "fastgen"
version = "0.2.1"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
tera = "1.17" # ou handlebars = "4.3"
fs_extra = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
rand = "0.8"
