name: Release Build

on:
  push:
    tags:
      - 'v*'  # Exemplo: v1.0.0

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release --verbose

      - name: Prepare artifacts
        run: |
          mkdir -p dist
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp target/release/fastgen.exe dist/fastgen-${{ runner.os }}.exe
          else
            cp target/release/fastgen dist/fastgen-${{ runner.os }}
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fastgen-${{ runner.os }}
          path: dist/
