name: Publish Release

on:
  release:
    types: [created]

jobs:
  upload:
    name: Upload binaries to GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Upload Linux binary
        uses: softprops/action-gh-release@v1
        with:
          files: fastgen-Linux/fastgen-Linux

      - name: Upload Windows binary
        uses: softprops/action-gh-release@v1
        with:
          files: fastgen-Windows/fastgen-Windows.exe

      - name: Upload macOS binary
        uses: softprops/action-gh-release@v1
        with:
          files: fastgen-macOS/fastgen-macOS
