name: Build & Release fastgen

on:
  push:
    tags:
      - 'v*'  # Ex: v1.0.0

jobs:
  build:
    name: Build fastgen binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build release
        run: cargo build --release

      - name: Upload release binary
        uses: actions/upload-artifact@v3
        with:
          name: fastgen-${{ runner.os }}
          path: |
            target/release/fastgen.exe
            target/release/fastgen
