name: Build fastgen binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release
        run: cargo build --release

      - name: Rename binary
        run: |
          mkdir output
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp target/release/fastgen.exe output/fastgen-${{ runner.os }}.exe
          else
            cp target/release/fastgen output/fastgen-${{ runner.os }}
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fastgen-${{ runner.os }}
          path: output/
