name: Release Linux Binary

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Package binary
        run: |
          mkdir dist
          cp target/release/fastgen dist/
          cd dist && zip fastgen-linux.zip fastgen

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/fastgen-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
